# Generated by Django 4.2.2 on 2023-08-08 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('agence de voyage', 'Agence de voyage'), ('association', 'Association'), ('e/se privee', 'E/se privee')], max_length=20)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('chambre_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('chambre_type', models.CharField(choices=[('indiv', 'indiv'), ('double', 'double'), ('triple', 'triple'), ('quadruple', 'quadruple')], max_length=30, null=True)),
                ('chambre_Vue', models.CharField(choices=[('Vue picine', 'Vue picine'), ('normal', 'nomal')], max_length=30, null=True)),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('codeclient', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nomclient', models.CharField(max_length=30, null=True)),
                ('typeclient', models.CharField(choices=[('indiv', 'indiv'), ('agence de voyage', 'agence de voyage'), ('privé', 'privé'), ('groupe', 'groupe')], max_length=20, null=True)),
                ('vchambre_type', models.CharField(choices=[('indiv', 'indiv'), ('double', 'double'), ('triple', 'triple')], max_length=30, null=True)),
                ('vchambre_vue', models.CharField(choices=[('Vue picine', 'Vue picine'), ('normal', 'nomal')], max_length=30, null=True)),
                ('date_arrivv', models.DateField(default=django.utils.timezone.now)),
                ('date_sortiee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('num_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('nationalite', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menugenerale.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Reservationgroube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('pension', models.CharField(choices=[('demi pension', 'demi pension'), ('pension complet', 'pension complet')], max_length=20, null=True)),
                ('categorie', models.CharField(choices=[('indiv', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=30, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Menugenerale.association')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationOccupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.chambre')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.occupant')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.reservationgroube')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationGroubeFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_assi', models.CharField(max_length=30)),
                ('nom_assi', models.CharField(max_length=100)),
                ('date_reservation', models.DateField()),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('pension', models.CharField(choices=[('demi pension', 'demi pension'), ('pension complet', 'pension complet')], max_length=20, null=True)),
                ('categorie', models.CharField(choices=[('indiv', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=30, null=True)),
                ('nbr_personne', models.IntegerField(default=0)),
                ('occupantslist', models.TextField(blank=True, null=True)),
                ('chambre_taked', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambre', models.ManyToManyField(blank=True, to='Menugenerale.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_personne', models.IntegerField(verbose_name='Number of People')),
                ('typeclient', models.CharField(blank=True, choices=[('indiv', 'indiv'), ('agence de voyage', 'agence de voyage'), ('privé', 'privé')], max_length=20, null=True)),
                ('codeagence', models.CharField(max_length=10, null=True)),
                ('date_arriv', models.DateField(blank=True)),
                ('date_sortie', models.DateField(blank=True)),
                ('type_pension', models.CharField(choices=[('pension complte', 'pension complte'), ('demi pension', 'demi pension')], max_length=20, null=True)),
                ('selected_clients', models.CharField(blank=True, max_length=100)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.chambre')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Menugenerale.client')),
            ],
        ),
        migrations.CreateModel(
            name='OccupantRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.occupant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.chambre')),
            ],
        ),
        migrations.AddField(
            model_name='occupant',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='Menugenerale.reservationgroube'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeclient', models.CharField(max_length=30)),
                ('nomclient', models.CharField(max_length=30)),
                ('date_arriv', models.DateField()),
                ('date_sortie', models.DateField()),
                ('chambre_id', models.IntegerField()),
                ('chambre_type', models.CharField(max_length=30)),
                ('chambre_vue', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambresingle_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambredouble_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambtriple_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('demipension_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pensioncomplte_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambresingle_price_season_a', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambredouble_price_season_a', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambtriple_price_season_a', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('demipension_price_season_a', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pensioncomplte_price_season_a', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('season_a_start_date', models.DateField()),
                ('season_a_end_date', models.DateField()),
                ('chambresingle_price_season_b', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambredouble_price_season_b', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambtriple_price_season_b', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('demipension_price_season_b', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pensioncomplte_price_season_b', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('season_b_start_date', models.DateField()),
                ('season_b_end_date', models.DateField()),
                ('chambresingle_price_season_c', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambredouble_price_season_c', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambtriple_price_season_c', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('demipension_price_season_c', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pensioncomplte_price_season_c', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('season_c_start_date', models.DateField()),
                ('season_c_end_date', models.DateField()),
                ('chambresingle_price_season_d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambredouble_price_season_d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambtriple_price_season_d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('demipension_price_season_d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pensioncomplte_price_season_d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('season_d_start_date', models.DateField()),
                ('season_d_end_date', models.DateField()),
                ('chambresingle_price_season_e', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambredouble_price_season_e', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chambtriple_price_season_e', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('demipension_price_season_e', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pensioncomplte_price_season_e', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('season_e_start_date', models.DateField()),
                ('season_e_end_date', models.DateField()),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.association')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champre_type', models.CharField(choices=[('indiv', 'indiv'), ('double', 'double'), ('triple', 'triple'), ('quadruple', 'quadruple')], max_length=30, null=True)),
                ('champre_Vue', models.CharField(choices=[('Vue picine', 'Vue picine'), ('normal', 'nomal')], max_length=30, null=True)),
                ('date_arriv', models.DateField()),
                ('date_sortie', models.DateField()),
                ('dispo', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.chambre')),
            ],
            options={
                'unique_together': {('chambre', 'date_arriv', 'date_sortie')},
            },
        ),
    ]
