# Generated by Django 4.2.4 on 2023-08-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_assi', models.CharField(max_length=30)),
                ('nom_assi', models.CharField(max_length=100)),
                ('date_reservation', models.DateField()),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('pension', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=30)),
                ('nbr_personne', models.CharField(max_length=100)),
                ('discounts', models.CharField(max_length=100)),
                ('discounts_detail', models.CharField(default='', max_length=100)),
                ('price_without_discount', models.CharField(max_length=100)),
                ('final_price_with_discount', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='associationcriteria',
            old_name='season_a_end_date',
            new_name='debut_contart',
        ),
        migrations.RenameField(
            model_name='associationcriteria',
            old_name='season_a_start_date',
            new_name='fin_contrat',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambredouble_price',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambredouble_price_season_a',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambredouble_price_season_b',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambredouble_price_season_c',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambredouble_price_season_d',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambredouble_price_season_e',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambresingle_price',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambresingle_price_season_a',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambresingle_price_season_b',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambresingle_price_season_c',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambresingle_price_season_d',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambresingle_price_season_e',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambtriple_price',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambtriple_price_season_a',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambtriple_price_season_b',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambtriple_price_season_c',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambtriple_price_season_d',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='chambtriple_price_season_e',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='demipension_price',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='demipension_price_season_a',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='demipension_price_season_b',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='demipension_price_season_c',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='demipension_price_season_d',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='demipension_price_season_e',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='pensioncomplte_price',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='pensioncomplte_price_season_a',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='pensioncomplte_price_season_b',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='pensioncomplte_price_season_c',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='pensioncomplte_price_season_d',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='pensioncomplte_price_season_e',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='season_b_end_date',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='season_b_start_date',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='season_c_end_date',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='season_c_start_date',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='season_d_end_date',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='season_d_start_date',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='season_e_end_date',
        ),
        migrations.RemoveField(
            model_name='associationcriteria',
            name='season_e_start_date',
        ),
        migrations.AddField(
            model_name='associationcriteria',
            name='monnaie',
            field=models.CharField(choices=[('TND', 'Dinar Tunisien'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservationgroubefinale',
            name='occupant',
            field=models.ManyToManyField(blank=True, to='Menugenerale.occupant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_pension',
            field=models.CharField(choices=[('pension complte', 'pension complte'), ('demi pension', 'demi pension'), ('LOG', 'log'), ('LPD', 'LPD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservationgroube',
            name='pension',
            field=models.CharField(choices=[('pension complte', 'pension complte'), ('demi pension', 'demi pension'), ('LOG', 'log'), ('LPD', 'LPD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservationgroubefinale',
            name='pension',
            field=models.CharField(choices=[('pension complte', 'pension complte'), ('demi pension', 'demi pension'), ('LOG', 'log'), ('LPD', 'LPD')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_season', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cat', models.CharField(choices=[('pension complte', 'pension complte'), ('demi pension', 'demi pension'), ('LOG', 'log'), ('LPD', 'LPD')], max_length=20, null=True)),
                ('demipension_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pensioncomplte_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('log_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lpd_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_threshold', models.PositiveIntegerField(default=0)),
                ('earlybooking_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('earlybooking_threshold', models.PositiveIntegerField(default=0)),
                ('mineur_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mineur_threshold', models.PositiveIntegerField(default=0)),
                ('association_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.associationcriteria')),
            ],
            options={
                'unique_together': {('association_criteria', 'start_date', 'end_date', 'cat')},
            },
        ),
    ]
