# Generated by Django 4.2.4 on 2023-08-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0002_facturefinale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='demipension_price',
            new_name='mineur2_discount',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='log_price',
            new_name='paxnum3_discount',
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='season',
            name='mineur2_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='paxnum3_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SeasonCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('pension complte', 'pension complte'), ('demi pension', 'demi pension'), ('LOG', 'log'), ('LPD', 'LPD')], max_length=20, null=True)),
                ('demipension_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pensioncomplte_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('log_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lpd_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menugenerale.season')),
            ],
        ),
        migrations.RemoveField(
            model_name='season',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='season',
            name='lpd_price',
        ),
        migrations.RemoveField(
            model_name='season',
            name='pensioncomplte_price',
        ),
    ]
