# Generated by Django 4.2.4 on 2023-08-14 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0003_rename_demipension_price_season_mineur2_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasoncategorie',
            name='cat',
            field=models.CharField(choices=[('single', 'single'), ('double', 'double'), ('triple', 'triple'), ('quaderiple', 'quaderiple')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seasoncategorie',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Menugenerale.season'),
        ),
    ]
