# Generated by Django 4.2.4 on 2023-08-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0004_alter_seasoncategorie_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasoncategorie',
            name='cat',
            field=models.CharField(choices=[('indiv', 'indiv'), ('double', 'double'), ('triple', 'triple'), ('quaderiple', 'quaderiple')], max_length=20, null=True),
        ),
    ]
