# Generated by Django 4.2.4 on 2023-08-15 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0005_alter_seasoncategorie_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationgroube',
            name='date_reservation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
