# Generated by Django 4.2.4 on 2023-08-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0006_alter_reservationgroube_date_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailability',
            name='name_pax',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='typeclient',
            field=models.CharField(choices=[('indiv', 'indiv'), ('privé', 'privé'), ('groupe', 'groupe')], max_length=20, null=True),
        ),
    ]
