# Generated by Django 4.2.4 on 2023-08-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0009_roomassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='code_assi',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='nom_assi',
            field=models.CharField(default='', max_length=30),
        ),
    ]
