# Generated by Django 4.2.4 on 2023-08-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0010_roomassignment_code_assi_roomassignment_nom_assi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paxes', to='Menugenerale.reservation')),
            ],
        ),
    ]
