# Generated by Django 4.2.4 on 2023-08-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0011_pax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pax',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='paxes',
            field=models.ManyToManyField(blank=True, to='Menugenerale.pax'),
        ),
    ]
