# Generated by Django 4.2.4 on 2023-08-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0012_remove_pax_reservation_reservation_paxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='chambre',
        ),
        migrations.AddField(
            model_name='reservation',
            name='chambre',
            field=models.ManyToManyField(blank=True, to='Menugenerale.chambre'),
        ),
    ]
