# Generated by Django 4.2.4 on 2023-08-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0013_remove_reservation_chambre_reservation_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='codeagence',
        ),
    ]
