# Generated by Django 4.2.4 on 2023-08-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0015_remove_reservation_nbr_personne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='selected_clients',
        ),
    ]
