# Generated by Django 4.2.4 on 2023-08-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0016_remove_reservation_selected_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_arrivv',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_sortiee',
        ),
    ]
