# Generated by Django 4.2.4 on 2023-08-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menugenerale', '0019_client_typepension_reservation_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='chambre_vue',
        ),
        migrations.AddField(
            model_name='facture',
            name='paxes',
            field=models.ManyToManyField(blank=True, to='Menugenerale.pax'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vchambre_type',
            field=models.CharField(choices=[('indiv', 'indiv'), ('double', 'double'), ('triple', 'triple')], max_length=30, null=True, verbose_name='Categorie'),
        ),
        migrations.RemoveField(
            model_name='facture',
            name='chambre_id',
        ),
        migrations.AddField(
            model_name='facture',
            name='chambre_id',
            field=models.ManyToManyField(blank=True, to='Menugenerale.chambre'),
        ),
    ]
