# Generated by Django 4.2.4 on 2023-08-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Menugenerale",
            "0021_alter_association_adress_alter_association_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roomassignment",
            name="reservation",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="roomavailability",
            name="reservation",
            field=models.CharField(default="", max_length=200),
        ),
    ]
