# Generated by Django 4.2.4 on 2023-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Menugenerale", "0022_roomassignment_reservation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="duration_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Long Stay Réduction",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="duration_threshold",
            field=models.PositiveIntegerField(default=0, verbose_name="Sejour >"),
        ),
        migrations.AlterField(
            model_name="season",
            name="earlybooking_threshold",
            field=models.DateField(verbose_name="Si"),
        ),
        migrations.AlterField(
            model_name="season",
            name="paxnum3_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Réduction pour 3 lit",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="paxnum3_threshold",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Seuil pour 3 lit"
            ),
        ),
    ]
