# Generated by Django 4.2.4 on 2023-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Menugenerale", "0024_inforamtionhotel_taxes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="vchambre_vue",
            field=models.CharField(
                choices=[("Vue picine", "Vue picine"), ("normal", "nomal")],
                default="",
                max_length=30,
                verbose_name="Vue",
            ),
        ),
    ]
