# Generated by Django 4.2.4 on 2023-08-31 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Menugenerale", "0025_alter_client_vchambre_vue"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assoctiontype", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="association",
            name="matfacial",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Matricule Fiscal"
            ),
        ),
        migrations.AddField(
            model_name="inforamtionhotel",
            name="marticule",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Matricule Fiscial"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="prix_force",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Prix Forcer"
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Menugenerale.associationtype",
            ),
        ),
    ]
