# Generated by Django 4.2.4 on 2023-09-10 21:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Menugenerale", "0026_associationtype_association_matfacial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pax",
            name="nationalite",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Nationalité"
            ),
        ),
        migrations.AddField(
            model_name="pax",
            name="num_telephone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numéro de téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="chambre",
            name="chambre_Vue",
            field=models.CharField(
                choices=[
                    ("Vue picine", "Vue picine"),
                    ("normal", "nomal"),
                    ("Vue sur mer", "Vue sur mer"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="type_pension",
            field=models.CharField(
                choices=[
                    ("pension complte", "pension complte"),
                    ("demi pension", "demi pension"),
                    ("LOG", "logement"),
                    ("LPD", "logement et petit dejeuner"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservationgroube",
            name="pension",
            field=models.CharField(
                choices=[
                    ("pension complte", "pension complte"),
                    ("demi pension", "demi pension"),
                    ("LOG", "Logement"),
                    ("LPD", "Logement et petit dejeuner"),
                ],
                max_length=20,
                null=True,
                verbose_name="Pension",
            ),
        ),
        migrations.AlterField(
            model_name="reservationgroubefinale",
            name="pension",
            field=models.CharField(
                choices=[
                    ("pension complte", "pension complte"),
                    ("demi pension", "demi pension"),
                    ("LOG", "Logement"),
                    ("LPD", "Logement et petit dejeuner"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roomavailability",
            name="champre_Vue",
            field=models.CharField(
                choices=[
                    ("Vue picine", "Vue picine"),
                    ("normal", "nomal"),
                    ("Vue sur mer", "Vue sur mer"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CombinedReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chosen_date", models.DateField(blank=True, null=True)),
                (
                    "reservation",
                    models.ManyToManyField(blank=True, to="Menugenerale.reservation"),
                ),
                (
                    "reservation_group",
                    models.ManyToManyField(
                        blank=True, to="Menugenerale.reservationgroubefinale"
                    ),
                ),
            ],
        ),
    ]
