# Generated by Django 4.2.4 on 2024-01-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Menugenerale", "0028_reservationgroubefinale_coc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationgroubefinale",
            name="coc",
            field=models.IntegerField(default=0),
        ),
    ]
